### ISSUE TITLE
Keep tokens after restaring the server

### ISSUE THREAD

**Issue by IvarsKarpics** [ispyb/py-ispyb#100]
Should we somehow (db, redis) keep tokens after restarting the server?

**Comment by antolinos** [comment]
A restart of the server should not kick out the people that are currently using the app. This is happening today and It is pretty appreciated by users.

I believe this should not be a built-in feature of py-ispyb but delegated to the authentication/s plugin.

**Comment by IvarsKarpics** [comment]
I made some changes (see PR #102 ) to the authentication. Previously I had to keep tokens because to get roles associated to the token (user). One can encode roles in the token and when user access the resource one can decode the token and get the roles immediately.
Somehow I am against of creating an external authentication plugin, because it raises the complexity. Each site has they own authentication systems and one can authenticate against them. If there is no authentication system then one can consider of creating one or, for example, use kong auth plugin.

Lets discuss this during the next web meeting

**Comment by antolinos** [comment]
There are potentially many different authentication mechanisms (OpenId, LDAP, etc...). By having all them on py-ispyb you are actually increasing the complexity of the project and adding unnecessary dependencies.
The code distributed in py-ispyb should be totally site-independent and each site should take care of its authentication mechanism.
Another reason is that I would prefer not to make public how our users are authenticated.
Something to be discussed...

**Comment by mgaonach** [comment]
deprecated
