### ISSUE TITLE
Improvements for database schema file (ispyb_ssx_db.sql)

### ISSUE THREAD

**Issue by KarlLevik** [ispyb/py-ispyb#113]
A couple of things that could be done better in the database schema file:

- The PK columns don't need to specify `UNIQUE` as they are already unique by virtue of being primary keys.
- The PK columns that have datatype `int` should be `int unsigned`. 
- It should be possible to declare the JSON columns as datatype `JSON` in MariaDB since version 10.2.7 and in MySQL since version 5.7.8. Note that in MariaDB the `JSON` keyword is just an alias for longtext something-something with a constraint that checks that it's valid JSON. This is fine, and should work as expected.
- I see there are table comments for a couple of the tables. It would be good to have something for all of them. 

I would also advise you to consider importing the current schema into a database, then exporting that using `mysqldump` (e.g. `mysqldump ispyb_ssx > ispyb_ssx_db.sql`), and then using that schema file in the repo instead of the one you have currently. The reason is that: a) the current schema file has separated the foreign key constraints from the `create table` statements, which makes it hard to read. b) Also, the `int`s don't have a specified number of digits (`int(10)`, `int(11)` etc), and different versions of MariaDB / MySQL might have different defaults for this, which could lead to errors. (The number of digits is really only used for presentation purposes, but it can still break foreign key constraint creation if the number is different between foreign key column and the column it's referencing.)

**Comment by stufisher** [comment]
Now over at https://github.com/ispyb/ispyb-database/pull/40
