### ISSUE TITLE
Version requirement on marshmallow_jsonschema

### ISSUE THREAD

**Issue by mgaonach** [ispyb/py-ispyb#116]
There is no version constraint for the requirement on marshmallow_jsonschema.
This can cause problem as some versions are not compatible with the specified version of marsmallow (for instance 0.13.0 generates the error bellow).
I suggest having a constraint (marshmallow_jsonschema==0.10.0 works just fine) to make sure we end up with a compatible version.

**Error with marshmallow_jsonschema 0.13.0:**
_ImportError: cannot import name 'INCLUDE' from 'marshmallow' (/usr/local/lib/python3.8/dist-packages/marshmallow/__init__.py)_

**Comment by IvarsKarpics** [comment]
Hi @mgaonach 
Thank you for reporting the issue. I will add the version number to the requirements.txt.
Ivars

**Comment by IvarsKarpics** [comment]
Solved with PR #117
