### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#130]
Other groups we work with are using black for code style, and flake8 for linting. I suggest these as standard unless there are any objections, and then enforce these in CI

We could use mypy, but maybe in the future...

**Comment by stufisher** [comment]
Also need to add these:
https://gitlab.esrf.fr/ui/daiquiri/-/blob/master/setup.cfg#L75

to stop flake8 and black conflicting

**Comment by mgaonach** [comment]
@stufisher can it be closed?

**Comment by stufisher** [comment]
Yep!
