### ISSUE TITLE
Problem with yaml load for auth settings

### ISSUE THREAD

**Issue by mgaonach** [ispyb/py-ispyb#144]
File "/users/gaonach/git/py-ispyb/./pyispyb/config.py", line 43, in <module>
    yaml_settings.update(yaml.safe_load(f, Loader=yaml.FullLoader))
TypeError: safe_load() got an unexpected keyword argument 'Loader'

**Comment by mgaonach** [comment]
@stufisher I think you modified that in #137 ?

**Comment by stufisher** [comment]
Urgh, sorry!
