### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#147]
Add a contributing.md with instructions on project guidelines, code style, review process, etc.

**Comment by mgaonach** [comment]
First we need to define what the contribution rules are with the collaboration.

Here is a suggestion:

- **All contributions to master can only be done through a pull request**
- **A pull request can only be merged with the following conditions**
  - **CI (`GitHub actions`) checks were successful**
  - **A `code owner` approved it**

We can achieve and enforce this automatically with GitHub features:
- We can create [teams](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams) listing the responsibles for each main part of the project (as agreed in the working group distribution spreadsheet)
- Then we can assign sections of the project's code to each of these teams as [code owner](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).
For instance `pyispyb/app/extensions/auth` to the `authentication` team.

-> Pull requests will then get automatically assigned for review to the members of the code owner team(s) and can only be merged when one of the member approved it.

⚠️ This will require converting the `ispyb` GitHub account into an organization account, as these features are not available with standard account. Conversion is free and easy.

**Comment by stufisher** [comment]
Yes, sorry, this was an invitation for discussion!

Some more suggestions:

* clear succinct commit messages along with reference to related issue
* squash commit for MRs, i.e. a single commit with a short description. Makes browsing commit history easier

**Comment by mgaonach** [comment]
From MXCuBE rules:

- MXCuBE has been relatively flexible about the rules for Pull Requests,
but it has been a minimum commitment that a Pull Request could *not* be
accepted before it had been reviewed and accepted by someone from a
*different* group.

Using simplified GitFlow : https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow
