### ISSUE TITLE
Remove ESRF references from LDAP authentication plugin

### ISSUE THREAD

**Issue by antolinos** [ispyb/py-ispyb#150]
There are some ESRF references in the LDAP authentication plugin that should be removed:
https://github.com/ispyb/py-ispyb/blob/a4d0711771811326cedc7193eb4fcb63555838d7/pyispyb/app/extensions/auth/LdapAuthentication.py#L94

**Comment by mgaonach** [comment]
I also see that the example configuration defines `LDAP_BASE_INTERNAL` and `LDAP_BASE_EXTERNAL` whereas the code refers to `LDAP_BASE_INTERNAL` and `LDAP_BASE_GROUPS`.
Probably `LDAP_BASE_GROUPS` has been replaced by mistake in the configuration at some point...

**Comment by mgaonach** [comment]
As previously discussed, the code for the LDAP plugin might still be specific to ESRF:
It authenticates users from a directory and then looks inside another directory for the groups. Some facilities might have a different procedure with different directories. We need to compared it and see if we can make something more generic.
