### ISSUE TITLE
flake8 plugin for naming conventions

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#155]
From https://github.com/ispyb/py-ispyb/issues/142 we should be able to build a custom flake8 plugin for our naming conventions built on:
https://github.com/PyCQA/pep8-naming

background:
https://flake8.pycqa.org/en/latest/plugin-development/index.html#video-tutorial

**Comment by rhfogh** [comment]
As noted elsewhere, can I propose using Black instead? https://black.readthedocs.io/en/stable/index.html An autoformatter (so does teh work for you) a strict subset of PEO8, and slightly longer lines (88 chars) which shortens files.

**Comment by stufisher** [comment]
We already use black, but linting is useful in addition to style enforcement in my opinion. Maybe not as many plugins as were installed before but at least the base flake8 is useful to catch extraneous imports and other standard things
