### ISSUE TITLE
Save server and client configuration in db

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#158]
There is a long standing ticket in SynchWeb to move the configuration out of some horrible php config file and into the database., similar to how wordpress works (https://wordpress.com/support/dashboard/). This way the only configuration that is needed is a couple of env vars for the db and the auth config to boot the backend. Then everything else can be configured at run time which doesnt require your devops team to redeploy your container / server when you want to change a config option. `AdminVar` could be used for this purpose storing dumped json in the `value` to allow more complex data structures.

It would be sensible for the UI to read this configuration information as well so it doesn't need its own config file. This is how daiquiri works, the server sends it the relevant config information, this means there is a single source of truth.

**Comment by mgaonach** [comment]
## July 6th 2022 framework meeting:
This was agreed to be a good idea, but needs extra investigation on how much changes are necessary in the database to allow that.
