### ISSUE TITLE
Decide how to handle site-specific features

### ISSUE THREAD

**Issue by mgaonach** [ispyb/py-ispyb#161]
We need to decide how to handle site-specific features:

- Have them in this repository
  - how to separate them from the generic code?
- Have them in external repositories
  - how to use this external code?

**Comment by stufisher** [comment]
Do you have an example of what a site specific feature is?

**Comment by antolinos** [comment]
This is an interesting subject for framework working group. In ISPyB we have some pieces of code that are site specific. A couple of examples that come to my mind are the authentication and UP synchronization.

Here, just one example:
https://github.com/ispyb/ISPyB/tree/master/ispyb-ws/src/main/java/ispyb/ws/rest/security/login

This makes code that is specific and not usable for other sites ends up in the main repository. Also, someone might not want that certain specific code gets public in github.

I like the approach they took in the `icatproject`. The software is based in components therefore you are not forced to put your own components in the main repository.
https://icatproject.org/about/components-of-the-icat-project

I think this approach might be cleaner.

**Comment by stufisher** [comment]
Ahh i see. I guess it depends what of this can be made configurable vs static code. For example an LDAP authenticator should be made configurable enough that it can handle any site -> kept in central code, but yes would be nice to separate more bespoke authentication methods (i.e. soleil).

`auth.yml` can specify an absolute python module so there should be no problem for it to come from another package.

**Comment by stufisher** [comment]
Can be implemented with https://github.com/ispyb/py-ispyb/issues/247
