### ISSUE TITLE
requirements.txt for multiple environments

### ISSUE THREAD

**Issue by clemenbor** [ispyb/py-ispyb#167]
Here at DESY we are still discussing if we will use a custom authentication mechanism or LDAP.

Currently the main requirement.txt file includes the packages for keycloack, ldap, etc.

I was wondering if it would make sense to have an approach for the requirements like this one:
https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments

...the common.txt file would include only the packages needed by everyone and then, for example, one can have a file "esrf.txt" where you add the packages specific to the facility. 

What you think?

**Comment by mgaonach** [comment]
## July 6th 2022 framework meeting:
This could bring unnecessary complexity in the dependency management. It was decided to wait and see if becomes necessary when the project grows.
