### ISSUE TITLE
Port daiquiri-rest-client

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#184]
Would like to port and adapt the daiquiri-rest-client into pyispyb: https://gitlab.esrf.fr/ui/daiquiri/-/blob/master/daiquiri/cli/rest.py
This lets you make arbitrary REST requests against the API with login, and see the results, useful for testing

**Comment by mgaonach** [comment]
Not sure to get it right, but is this not something already provided by `fastapi.testclient` for tests, and by the OpenAPI UI on `/docs` for developments?
