### ISSUE TITLE
How to integrate ispyb with mxcube?

### ISSUE THREAD

**Issue by laoniu2020** [ispyb/py-ispyb#191]
Hi,

 I'm confused by how to integrate ispyb with mxcube.

 Is it right that py-ispyb need work together with [py-ispyb-ui](https://github.com/ispyb/py-ispyb-ui).

I notice the py-ispyb project introduction is ISPyB backend server based on FastAPI.
My question is what's the different between ispyb and py-ispyb?  They have identical functions?

Could someone give me some pointers.

Thanks

**Comment by bodinm** [comment]
Hello, 

[ISPyB](https://github.com/ispyb/ISPyB) is the original project. It contains
- a backend in JAVA
- a database
- a front-end, JSP pages embedded (deprecated)

We want to migrate the JAVA back-end to python: it's the [py-ispyb](https://github.com/ispyb/py-ispyb) project. As you mentioned, it is based on FastAPI. 

We have multiple front-ends depending on the different facilities:
- SynchWeb, in php 
- EXI, in javascript
- EXI2, based on React

In the context of the ISPyB collaboration, we also want to develop a front-end, this is the [py-ispyb-ui](https://github.com/ispyb/py-ispyb-ui) project. Our goal is that py-ispyb can be used with py-ispyb-ui, but also with the active front-ends, like EXI or SynchWeb. For this purpose, we are developing in py-ispyb a legacy API, to maintain the compatibility.

Hope it helps,

**Comment by laoniu2020** [comment]
Thank you very much. This helped me a lot.
So does that mean if we choose to use pyispyb at our beamline, the Java version of ispyb doesn’t need to be set up?

**Comment by bodinm** [comment]
Theoretically yes, but, for now, only a part of the web services have been migrated, and in particular, those used by MXCuBE are not yet in py-isypb. So I'm afraid that if you want to use MXCuBE/ISPyB now, you need to install the java backend.
