### ISSUE TITLE
Authentication mechanism

### ISSUE THREAD

**Issue by antolinos** [ispyb/py-ispyb#2]
Hi @IvarsKarpics, 

Have you already thought about authentication and authorization mechanisms? Something I really don't like from ISPyB today is that the code is inside ISPyB itself or it is managed by Wildfly.
Could we envisage that ISPyB connects to an authentication module that lives outside of ISPyB?

Thanks,
A.

**Comment by IvarsKarpics** [comment]
Hi @antolinos . I thought it could be something similar to tokens used currently in ispyb. But it is worth to look at some other existing solutions.

**Comment by antolinos** [comment]
Yes. Once a user has the token ISPyB can work as today. However, the software that will produce the token should not be in ISPyB but site-specific. We need just to implement an interface that will return a valid token from valid credentials.
This will avoid to have all LDAP, keycloak, OpenID, etc... configurations from all sites inside of ISPyB
