### ISSUE TITLE
mysql-connector-python==8.0.29 in requirements.txt, but not in setup.cfg

### ISSUE THREAD

**Issue by KarlLevik** [ispyb/py-ispyb#218]
Should this line specify version 8.0.29, just like in requirements.txt?
https://github.com/ispyb/py-ispyb/blob/4d48f7f393c7949ea49956b254783f2e46cca5dc/setup.cfg#L47

**Comment by stufisher** [comment]
Yes, feel free to make a pr, thanks!

**Comment by KarlLevik** [comment]
I also see that the project depends on `mysql-connector` in addition to `mysql-connector-python`.

Apparently, `mysql-connector` is just an older version of what is now `mysql-connector-python`:
https://github.com/pypi/warehouse/issues/5537

So we should probably remove `mysql-connector` from the `requirements.txt` and `setup.cfg` files.
