### ISSUE TITLE
Mock of Database

### ISSUE THREAD

**Issue by antolinos** [ispyb/py-ispyb#3]
Hi @IvarsKarpics,

For unit and integration testing, would it be convenient to be capable to mock a MariaDB instance with synthetic data?
We could enrich such database with different use cases. If so, I can have a look at it.

Cheers,
A.

**Comment by IvarsKarpics** [comment]
Hi @antolinos 

I added this already to the travis.yaml:
https://github.com/IvarsKarpics/ispyb_backend_prototype/blob/40909d4ec601e3c06372b06375e8e6a40a2ec941/.travis.yml#L11-L25
It is taken directly from DLS ispyb-api.
Now there is not so much test. I run just pylint to check python syntax, but when the backend gets mature we can add more test.

**Comment by antolinos** [comment]
I wonder if it should not be taken the official database schema
