### ISSUE TITLE
Endpoint Design

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#36]
Thanks for putting this together, this is looking good. Below some general discussion on endpoint design, related to the document than @drnasmith put together for api spec.

```
    /prop/list
    /prop/get_by_person
    /prop/<proposalid>
```
These three resources all return the same payload. The design of using different resources for different filters is historic and it is not very REST like. It also makes consuming the api complicated because you must use different endpoints to ultimatly access the same resource. 

Most REST guidelines suggest these should be a single resource, with query parameter filters. Right now the queries are very simple, but once you add authorisation these will grow in complexity, by making these a single resource you will significantly reduce code duplication later. In synchweb we have a single resource per table so there is only ever one source of truth, it makes maintainace much simpler.

Also if you read REST guidlines they suggest using plural nouns, rather than things like /list, /get and the likes so we should go for something like
```
/proposals
/proposals/<proposalid>
/proposals?login=<login>
/proposals?active=1
```

With sqlaclhemy you can actually share the query for the single and list case with some pretty succint code:
```
    query = Proposals.query

    if login:
        query = (query
            .join(PersonModel, PersonModel.personid=Propsals.personid)
            .filter_by(PersonModel.login=login)
        )


    if proposalid:
        query = query.filter_by(proposalid=proposalid)
        proposal = query.first()
        if not proposal:
            return { "error": "No such proposal" }, 404
        else
            return proposal
    else:
        proposals = query.all()
        return ...
```

I would also suggest that right from the start you paginate every resource, ive found throughout writing synchweb that if you start with non paginated resources they all grow to the point they need paginating. Best to do this from the off, and its really easy with sqlalchemy:
```
    total = query.count()
    query = query.limit(lims["per_page"]).offset(lims["st"])
    proposals = query.all()

    return {"total": total, "rows": proposals}
```
Looks like there is actually a paginate function in flask_sqlalchemy?

The endpoints also return simple structures at the moment, these will also grow in complexity, the best part of using a relational database is we know the relations, with proposals you want to know how many sessions, maybe samples, datacollections, etc. This is also really nicely done with sqlalchemy, it will often be able to infer the relationship, so you can just do:
```
    query = Proposals.query

    query = (
        .join(BLSession).add_columns(func.count(BLSession.session).label("sessions"))
    )
```

**Comment by IvarsKarpics** [comment]
Hi @stufisher 

Thanks for the deep comment on the end point design. I looked up the rest guidlines and will start with proposals and example. In general the idea is to start with one namespace and agree upon it.
I will move comments about pagination to another issue.

**Comment by stufisher** [comment]
Superseeded with fastapi. New routes use this endpoint style and query parameters
