### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#37]
At the moment the queries dont have any authorisation, this is a big part of ISPyB. For every resource you need to enforce a linkage right through to either:
* Session_has_Person to know what user has access to what.
* Some sort of admin/staff check (further discussion below)

In synchweb i check for a dcid or proposal parameter, and use this to check the user has access before getting in to doing a resource query. I still always join the proposal right through as well in the queries, you can check this out in the synchweb source code. It would be worth working out how to do this in a generic way and apply it to all routes.

This means that all queries are tied to a proposal, and in synchweb we find that sometimes we want to access resources in an administrative way i.e. see all shipments from all proposals.

The basic authorisation scheme is:
* A user can only access data if they were on the session i.e. Session_has_Person
* We follow this for proposals too, the user must exist in Session_has_Person in order to access the proposal
* There is also a Proposal_has_Person table, which is unused in Synchweb, we should think about whether this should be implemented. There are cases where you might want to register a shipment before a session exists.

I dont know if you use proposal login at EMBL, but this is a special case and should not be the norm. If it is really needed it should rely on a Session_has_Person entry for a person with login of the proposal. Really, we should enforce user login, so we know who is logged in and what they are doing.

Roles / UserGroup:
------------------
At the moment the official java api uses roles to identify staff types, in my opinion these are way too primitive. At diamond we use UserGroup, Permission, UserGroup_has_person, and UserGroup_has_permission to enable fine grained access to specific resources. If you are making a scalable python api from scratch i would suggest you use this approach and add a specific permission to each endpoint. This lets you build complex access rights cleanly and simply. You can also admin them from within the api as we do in synchweb

**Comment by antolinos** [comment]
@stufisher 
I agree that the current way is quite primitive, it was done 20 years ago. I am interested in knowing more about how you use the Permission. 
Some questions came to my mind:
Do you know where can I find documentation about it?
 What is the level of granularity of the permissions? 
Can data be made public? 
Anonymous access?

**Comment by stufisher** [comment]
Like all of ispyb there is no documentation ;)

There are four tables
Permission
UserGroup
UserGroup_has_Person
UserGroup_has_Permission

This allows us to construct groups of users with fine grained permissions. The synchweb api and client checks for specific `Permission` entries to allow you to do things, this means we can create very specific groups.

Re your second question, anonymous access could be granted by simply adding a new "anonymous" user in Session_has_Person. 

Synchweb only allows users with an entry in Session_has_Person to view the data of a particular session. I guess you will have to implement this in the java api as well for the data confidentiality protocol. However care would need to be taken to make this user read only. Right now in Synchweb anyone on a session in the proposal can view and edit all of the samples / shipments in that proposal.

**Comment by antolinos** [comment]
> Like all of ispyb there is no documentation ;)

It seems that ISPyB and Synchweb are well aligned on this subject

I see a Permission table but not sure is the one you are using:
```
CREATE TABLE `Permission` (
  `permissionId` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(15) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`permissionId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
Type is just a VARCHAR. Which are the distinct values of the column type on the Permission table?

**Comment by stufisher** [comment]
Yes these tables were merge when the dls / esrf merger happened a few years back. 
You can find the defaults here:
https://github.com/DiamondLightSource/ispyb-database/blob/master/schema/lookups.sql#L151

**Comment by antolinos** [comment]
There are 80 entries as far as I can see.
```
(1,'mx_admin','MX Administrator'),
(2,'manage_groups','Manage User Groups'),
(4,'manage_perms','Manage User Group Permissions'),
(5,'global_stats','View Global Statistics'),
(6,'fault_view','View Fault Reports'),
(7,'saxs_admin','SAXS Administrator'),
(8,'em_admin','EM Administrator'),
(9,'gen_admin','Powder Admin'),
(10,'tomo_admin','Tomo Admin'),
(11,'super_admin','Site Admin'),
(12,'fault_global','Globally edit all faults'),
[.....]
```

If I am not mistaken it seems to me that MX_Administrator, manage_groups,  manage_perms, etc.. is a sort of declaration of roles with finer granularity. Similar to what ISPyB does today but instead of having only 4 roles you are using 80.

Do you think it would be possible to use this mechanism to be compliant with the data policy, for instance, making a subset of data (publicly available?

**Comment by stufisher** [comment]
Roles correct my if im wrong, are a set a permissions in the java api. A permission in synchweb gives access to one specific function, or maybe a set of CRUD functions, i.e. much more fine grained. There are 30 permissions at the moment, primary key increments by 3 on the cluster.

I think for your data policy question its better addressed using Session_has_person, but needs read only attribute, and some way to apply that.

**Comment by mgaonach** [comment]
deprecated
