### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#38]
Minor point, jwts usually go in the Authorization: Bearer {jwt} header

Also, every route apart from the login one probably wants @token_required, might want to add this automatically along with @api.doc(security="apikey")?

**Comment by IvarsKarpics** [comment]
Sure, `@api.doc(security="apikey")` and `@token_required` will be on all (except /auth/login) routes and look like:

```
@api.route("/list")
@api.doc(security="apikey")
class ProposalList(Resource):
    """Allows to get all proposals"""

    @api.marshal_list_with(proposal.schemas.f_proposal_schema)
    @token_required
    def get(self):
        """Returns all proposals"""
        log.info("Return all proposals")
        return proposal.get_all_proposals()

    @api.expect(proposal.schemas.f_proposal_schema)
    @api.marshal_with(proposal.schemas.f_proposal_schema, code=201)
    def post(self):
        """Adds a new proposal"""
        log.info("Insert new proposal")
        proposal.add_proposal(**api.payload)
```

One other question is the name and location of the token:
* token, X-API-KEY, jwt.
* header, queries and/or cookies 
I vote for name token and location header, queries.

**Comment by stufisher** [comment]
As i mentioned above, the jwt guidlines say:
Header only => Authorization: Bearer {jwt}
https://jwt.io/introduction/ scroll down to "How do JSON Web Tokens work?"

Tokens should not be used in url or query parameters, see:
https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html#sensitive-information-in-http-requests

The only time i used a token in a query param is a one time token for accessing download resources when you cant use a header. This as the name implies can be used once and is then invalidated

**Comment by IvarsKarpics** [comment]
Ok. So the wrapper function could look like? :

```
def token_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token = None

        if "Authorization" in request.headers:
            # Bearer <jwt token>
            token = request.headers["Authorization"].split(' ')[1]
        if not token:
            return {"message": "Token is missing."}, 401

        Check if the token is valid...
```
