### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#39]
You can transform all of the marshmallow models into json-schema models automatically using:
https://github.com/fuhrysteve/marshmallow-jsonschema

This is awesome because now we have a single source of models, in synchweb we have to maintain a model in the front end, and php api to enforce validation. 

You can now use these json-schema models to automatically generate forms with the proper validation:
https://github.com/rjsf-team/react-jsonschema-form

**Comment by mgaonach** [comment]
deprecated
