### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#40]
Another important part of ISPyB  is input and validation. This is great that you are already using marshmallow and the likes, however its worth looking a bit deeper into the validation. I find that string is usually not a sufficient validator. Protein acronym often ends up in the file system and should be constrained to something along the lines of an [A-z0-9]+ regexp. These are easy to build with marshmallow, so we should probably build a compilation of useful ones.

I use something along the lines of:
```
def ValidatedRegexp(pattern, **kwargs):
    expressions = {
        "word": "^[A-z0-9]+$",
        "word-dash": "^[A-z0-9-]+$",
        "word-dash-space": "^[\w\s-]+$",
    }

    if pattern in expressions:
        validates = kwargs.pop("validate", None)
        if validates and type(validates) != list:
            validates = [validates]

        return fields.Str(
            pattern=expressions[pattern],
            validate=[
                validate.Regexp(
                    expressions[pattern],
                    flags=0,
                    error="Input {input} does not match {regex}",
                )
            ]
            + (validates if validates else []),
            **kwargs
        )
    else:
        raise Exception(f"Cant find regular expression for {pattern}")
```

I was also thinking about how say shippingid, proposalid, etc, is always the same, and it would be good to build an assortment of these that can be reused. Not quite sure how to do this, but it would be nice to be able to define:
```
propsalid = fields.Int()
```
and reuse that through the models. Some thought needed on how to organise that.

**Comment by mgaonach** [comment]
@stufisher is this still up to date with FastAPI?

**Comment by stufisher** [comment]
It would be good to build some of the standard regexp fields. I will have to check where i got to
