### ISSUE TITLE
Error Handling / Status Codes

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb#41]
Reading through i think you have some of this already, but its also worth getting error handling set up in a standardised way, in another project i have a
```
ErrorSchema(Schema):
    error = fields.Str()

MessageSchema(Schema):
    message = fields.Str()
```
Now if you use the same schema everywhere we have standardised response types.

We should think about http status codes too:
422 = malformed payload, you should get this from an invalid marshmallow model i think?
401 = unauthorised
403 = no proposal maybe?
404 = not found
201 = created (say new proposal)
200 = ok, normal

we should avoid sending 500, the user should never see a 500, this is an uncaught exception.

**Comment by IvarsKarpics** [comment]
What about a dict with error codes in the config.py? Maybe something like:
```
ERROR_CODES = {"success": 200,
"created": 201,
...
```

**Comment by IvarsKarpics** [comment]
Ah forgot the previous comment. Status codes are here:

`from flask_restx._http import HTTPStatus`

**Comment by mgaonach** [comment]
@stufisher is this still up to date with FastAPI?

**Comment by stufisher** [comment]
The new routes return standard codes i think
