### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by IvarsKarpics** [ispyb/py-ispyb#42]
Original issue: #36 

I would also suggest that right from the start you paginate every resource, ive found throughout writing synchweb that if you start with non paginated resources they all grow to the point they need paginating. Best to do this from the off, and its really easy with sqlalchemy:
```
    total = query.count()
    query = query.limit(lims["per_page"]).offset(lims["st"])
    proposals = query.all()

    return {"total": total, "rows": proposals}
```
Looks like there is actually a paginate function in flask_sqlalchemy?

The endpoints also return simple structures at the moment, these will also grow in complexity, the best part of using a relational database is we know the relations, with proposals you want to know how many sessions, maybe samples, datacollections, etc. This is also really nicely done with sqlalchemy, it will often be able to infer the relationship, so you can just do:
```
    query = Proposals.query

    query = (
        .join(BLSession).add_columns(func.count(BLSession.session).label("sessions"))
    )
```

**Comment by IvarsKarpics** [comment]
The question is how the pagination should be reflected in the end point: Should it be:
* `/ispyb/api/v1/proposals?page=1` or
* `/ispyb/api/v1/proposals/page/1`

**Comment by stufisher** [comment]
The second, and i think the maybe offset and limit, rather than page. Keep the endpoint url simple, use query parameters. @drnasmith?

**Comment by IvarsKarpics** [comment]
Okay.
